[package]
name = "pdfuse-sizing"
version = "1.0.0"
edition = "2021"

[dependencies]
once_cell = "1.20.2"
printpdf = "0.7.0"
regex = "1.11.1"
serde = { version = "1.0.215", features = ["derive"] }

[lints]
workspace = true
