[package]
name = "pdfuse"
version = "0.9.0"
edition = "2024"
[workspace]
resolver = "2"
members = [ 
"pdfuse-commandline",
    "pdfuse-merging",
    "pdfuse-parameters",
    "pdfuse-sizing",
    "pdfuse-utils",
]

[workspace.dependencies]
log = "0.4.29"
indicatif = {version= "0.18", features = ["rayon"]}
rust-i18n = "3.1.5"
serde = { version = "1.0.228", features = ["derive"] }
rayon = "1.11.0"
regex = "1.12.3"
anyhow = "1.0.101"
tabled = "0.20.0"
thiserror = "2.0.18"
toml = "1.0.3"
clap = { version = "4.5.57", features = ["derive"] }
color-print = "0.3.7"
image = "0.25.9"
dashmap = "6.1.0"
walkdir = "2.5.0"
dirs = "6.0.0"
chrono = "0.4.43"
indoc = "2"
serde_json = "1.0.149"
derive_more = {version =  "2.1.1", features = [
   "add",
   "add_assign",
   "display",
   "eq",
   "mul",
   "not",
   "from_str",
   "mul_assign"
] }
lopdf = {version = "0.39.0", features = [
"image",
"embed_image",
] }
# printpdf = { version = "0.9.1", features = [
#     "bmp",
#     "gif",
#     "jpeg",
#     "png",
#     "pnm",
#     "tga",
#     "tiff",
#     "webp",
#     "ico",
# ] }

[workspace.lints.clippy]



[dependencies]
pdfuse-sizing = { path = "pdfuse-sizing" }
pdfuse-utils = { path = "pdfuse-utils" }
pdfuse-merging = { path = "pdfuse-merging" }
pdfuse-parameters = { path = "pdfuse-parameters" }
pdfuse-commandline = { path = "pdfuse-commandline" }
clap.workspace = true
color-print.workspace = true
rust-i18n.workspace = true
lopdf.workspace=true
walkdir.workspace = true
tabled.workspace = true
image.workspace = true
dashmap.workspace = true
rayon.workspace = true
indicatif.workspace = true
log.workspace = true
regex = {workspace = true}
dirs.workspace = true
toml.workspace=true
serde_json.workspace = true
anyhow.workspace = true

[package.metadata.i18n]
available-locales = ["en", "pl"]
default-locale = "en"
load-path = "locales"

[profile.release]
strip = true
lto = "thin"


[profile.dev]
# opt-level=1
[profile.dev.package."*"]
opt-level=3
#debug=true
#split-debuginfo="unpacked"

#[target.x86_64-pc-windows-gnullvm]
#linker = "clang"
# [lib]
# name = "pdf_test_lib"
# path = "src/lib.rs"

# [[bin]]
# name = "pdf_test_bin"
# path = "src/main.rs"

# [profile.release]
# strip = true
