[package]
name = "pdfuse-parameters"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.57", features = ["color","derive","cargo","unicode","wrap_help","usage","help","error-context","suggestions","string"] }
pdfuse-sizing = { path = "../pdfuse-sizing" }
pdfuse-utils = { path = "../pdfuse-utils" }
dirs = "6.0.0"
rust-i18n.workspace = true
log.workspace = true
walkdir = "2.5.0"
thiserror.workspace=true
derive_more.workspace=true
indoc = "2"
color-print = "0.3.7"
serde.workspace=true
toml = { workspace=true, features = ["preserve_order"] }
chrono = "0.4.43"
regex.workspace=true
indicatif.workspace = true

[package.metadata.i18n]
available-locales = ["en", "pl"]
default-locale = "en"
load-path = "../locales"

[lints]
workspace = true
